const ProjectData = {
  AI_ML: [
    {
      name: "Lung cancer Prediction Model",
      image: "logo.png",
      type: "",
      dataset: "",
      desc: "",
      excerpt: "Simple LSTM",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "",
      type: "",
      dataset: "",
      desc: "",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "",
      type: "",
      dataset: "",
      desc: "",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "",
      type: "",
      dataset: "",
      desc: "",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "",
      type: "",
      dataset: "",
      desc: "",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "",
      type: "",
      dataset: "",
      desc: "",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "",
      type: "",
      dataset: "",
      desc: "",
      algo: "LSTM",
      challenges: "",
      resolution: "",
      outcome: "",
    },
  ],
};

export default ProjectData;
