const ProjectData = {
  AI_ML: [
    {
      name: "Lung cancer Prediction Model",
      image: "logo.png",
      type: "Classification",
      dataset: "so amd so",
      desc: "This model is ",
      excerpt: "Simple LSTM model used for predicting the ",
      algo: "LSTM",
      challenges: "asdjk jkasjdsadkj asdkasdasd",
      resolution: "asdasdasd",
      outcome: " 99% accuracy",
      gitrepo:
        "https://github.com/NeoMorpheus99/AI-ML/tree/2e11e1b5b70392b804c63f5c301f736b04d0b6fc/Lung%20Cancer%20Prediction%20Model",
      report: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "logo.png",
      type: "Classification",
      dataset: "so amd so",
      desc: " use of LSTM Model to deelop a model",
      excerpt: "Simple LSTM",
      algo: "LSTM",
      challenges: "asdjk jkasjdsadkj asdkasdasd",
      resolution: "asdasdasd",
      outcome: " 99% accuracy",
      gitrepo: "",
      report: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "logo.png",
      type: "Classification",
      dataset: "so amd so",
      desc: " use of LSTM Model to deelop a model",
      excerpt: "Simple LSTM",
      algo: "LSTM",
      challenges: "asdjk jkasjdsadkj asdkasdasd",
      resolution: "asdasdasd",
      outcome: " 99% accuracy",
      gitrepo: "",
      report: "",
    },
    {
      name: "Lung cancer Prediction Model",
      image: "logo.png",
      type: "Classification",
      dataset: "so amd so",
      desc: " use of LSTM Model to deelop a model",
      excerpt: "Simple LSTM",
      algo: "LSTM",
      challenges: "asdjk jkasjdsadkj asdkasdasd",
      resolution: "asdasdasd",
      outcome: " 99% accuracy",
      gitrepo: "",
      report: "",
    },
  ],
};

export default ProjectData;
